# Generated by Django 5.2.4 on 2025-08-11 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0004_alter_customuser_managers'),
        ('userfuncs', '0006_notification_title_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auther.ngo'),
        ),
    ]
