# Generated by Django 5.2.4 on 2025-08-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngofunc', '0006_alter_ngorequests_usersissuing'),
        ('userfuncs', '0007_alter_donation_ngo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='ngo',
        ),
        migrations.CreateModel(
            name='donationmapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_allocated', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userfuncs.donation')),
                ('ngo_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngofunc.ngorequests')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='ngoreq',
            field=models.ManyToManyField(blank=True, through='userfuncs.donationmapping', to='ngofunc.ngorequests'),
        ),
    ]
