# Generated by Django 5.2.4 on 2025-08-12 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0004_alter_customuser_managers'),
        ('userfuncs', '0008_remove_donation_ngo_donationmapping_donation_ngoreq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmapping',
            name='ngo_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auther.ngo'),
        ),
        migrations.AddField(
            model_name='donationmapping',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
