# Generated by Django 5.2.4 on 2025-08-12 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0009_donationmapping_ngo_user_donationmapping_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationmapping',
            name='donation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
