# Generated by Django 5.2.4 on 2025-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0010_donationmapping_donation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='recieved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending'),
        ),
    ]
