# Generated by Django 5.2.4 on 2025-08-08 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngofunc', '0002_remove_ngorequests_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngorequests',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='ngorequests',
            name='status',
        ),
        migrations.AddField(
            model_name='ngorequests',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ngorequests',
            name='submittedon',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
