# Generated by Django 5.2.4 on 2025-08-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngofunc', '0003_remove_ngorequests_request_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngorequests',
            name='recieved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
