# Generated by Django 5.2.4 on 2025-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngofunc', '0004_ngorequests_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngorequests',
            name='stats',
            field=models.CharField(choices=[('full', 'full'), ('pending', 'pending')], default='pending'),
        ),
    ]
